#!/usr/bin/env bash
MOUNTED="y"
INSTALLGRUB="n"
GRUBDESTDISK="/dev/does/not/exist"

_HOSTNAME=""

_TIMEZONE="Europe/Prague"

ROOTPASS=""
_USERNAME=""
USERPASS=""

SSHINSTALL="y"
NMINSTALL="n"
DOOOM="y"
DOSWAP="y"

SETUPTYPE="3"
